# Configuração do Dependabot para atualizações automáticas
version: 2
updates:
  # Atualizações de dependências npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "lucas-egswf"
    assignees:
      - "lucas-egswf"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignorar atualizações major que podem quebrar
      - dependency-name: "cypress"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@badeball/cypress-cucumber-preprocessor"
        update-types: ["version-update:semver-major"]

  # Atualizações do GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lucas-egswf"
    assignees:
      - "lucas-egswf"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
